### ISSUE TITLE
lammpsdatareader: Mass exceeds tolerance of match

### ISSUE THREAD

**Issue by junghans** [votca/csg#267]
With `spce.data` from [here](https://github.com/votca/csg-tutorials/blob/master/spce/ibi_lammps/spce.data), I get the following error:
```
$ csg_dump --top spce.data
an error occurred:
Mass exceeds tolerance of match
```
(found in https://github.com/votca/csg-tutorials/pull/24)

The fun part is that `spce.data` only has one mass in it.

**Comment by JoshuaSBrown** [comment]
Ok

**Comment by JoshuaSBrown** [comment]
Well I found the problem I assumed for some reason that all files coming from lammps would be purely atomistic for some reason no course graining. Thus when using the mass to match with an atom type it was rightly throwing an error. I will change this so that it able to distinguish between an element and a course grained molecule based on the mass.
