### ISSUE TITLE
Out of bounds error in csg_reupdate

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/csg#382]
https://github.com/votca/csg/blob/dd97ff3601c415706cd7468983f379105fd550cb/src/tools/csg_reupdate.cc#L691-L699

**Comment by junghans** [comment]
@symashayak can you have a look please?

**Comment by JoshuaSBrown** [comment]
My guess is that, this is what was meant: 

     for (int i = dist.size() - 2; i > 0; i--) { 
         if (dist.y(i) < 1.0e-4) { 
             new_min = dist.x(i + 1); 
             break; 
          } 
      }

**Comment by JoshuaSBrown** [comment]
@symashayak ping

**Comment by symashayak** [comment]
Not sure what is the error. Original loop bounds look good to me. Where are you seeing this error?

**Comment by JoshuaSBrown** [comment]
The first iteration was calling

 new_min = dist.x(dist.size);

which is an out of bounds error.

**Comment by symashayak** [comment]
Ok. I understand. This would happen when RDF (dist) is zero very close to
the cut-off distance.Wouldn't it be unrealistic to have an RDF value ~zero
close to the cut-off distance? In any case, to avoid this out of bounds
error, your solution of changing loop begin bound from  i = dist.size() - 1
to  i = dist.size() - 2 should work. However, in such rare case, even if we
avoid out of bounds error, I believe, relative entropy minimization
iteration might not proceed due to numerical instability in Hessian.

**Comment by JoshuaSBrown** [comment]
@symashayak thanks for the clarification, I just needed to know that the code fix I was proposing wasn't going to break anything.

**Comment by junghans** [comment]
Fixed in 75a2ad62744893bb07f1fa4538cd8df85a93433d
